import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { CartProvider } from "@/context/CartContext";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      {/* <ClerkProvider> */}
      <html lang="en">
        <body>
        {/* <SignedOut> */}
            {/* <SignInButton /> */}
          {/* </SignedOut> */}
          {/* <SignedIn> */}
            {/* <UserButton /> */}
          {/* </SignedIn> */}
         <Header/>
          {children}
          <Footer/>
        </body>
      </html>
    {/* </ClerkProvider> */}
    </CartProvider>
  );
}
